
version: '3.9'

services:
  web:
    build: .
    command: gunicorn dj.wsgi -b 0.0.0.0:8000  
    # command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=JfkctlHPS6WIW5x_2n6gYcMrQzdj8AgMfU69YQq8IIuNFGQZLXk"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

